# Generated by Django 2.2 on 2021-06-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Networks',
        ),
        migrations.AddField(
            model_name='shows',
            name='network',
            field=models.CharField(default='none', max_length=45),
        ),
    ]
